services:
  jellyfin:
    image: jellyfin/jellyfin:latest
    container_name: jellyfin

    network_mode: host

    volumes:
      - /opt/containers/jellyfin/config:/config
      - /opt/containers/jellyfin/cache:/cache
      - /mnt/storage/media:/media:ro

    restart: unless-stopped

  qbittorrent:
    image: lscr.io/linuxserver/qbittorrent:latest
    container_name: qbittorrent

    network_mode: host

    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Etc/UTC
      - WEBUI_PORT=8080

    volumes:
      - /opt/containers/qbittorrent/config:/config
      - /mnt/storage/media:/media

    restart: unless-stopped

  prowlarr:
    image: lscr.io/linuxserver/prowlarr:latest
    container_name: prowlarr

    network_mode: host

    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Etc/UTC

    volumes:
      - /opt/containers/prowlarr/config:/config

    restart: unless-stopped

  sonarr:
    image: lscr.io/linuxserver/sonarr:latest
    container_name: sonarr

    network_mode: host

    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Etc/UTC

    volumes:
      - /opt/containers/sonarr/config:/config
      - /mnt/storage/media:/media

    restart: unless-stopped

  radarr:
    image: lscr.io/linuxserver/radarr:latest
    container_name: radarr

    network_mode: host

    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Etc/UTC

    volumes:
      - /opt/containers/radarr/config:/config
      - /mnt/storage/media:/media

    restart: unless-stopped

  bazarr:
    image: lscr.io/linuxserver/bazarr:latest
    container_name: bazarr

    network_mode: host

    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Etc/UTC

    volumes:
      - /opt/containers/bazarr/config:/config
      - /mnt/storage/media:/media

    restart: unless-stopped

  syncthing:
    image: lscr.io/linuxserver/syncthing:latest
    container_name: syncthing

    network_mode: host

    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Etc/UTC

    volumes:
      - /opt/containers/syncthing/config:/config
      - /mnt/storage/media:/media

    restart: unless-stopped
